name: dart_sdp_transform
version: 0.0.1
author: cloudwebrtc <duanweiwei1982@gmail.com>
description: Dart implementation of sdp-transform
homepage: https://github.com/cloudwebrtc/dart-sdp-transform
environment:
  sdk: '<3.0.0'
dependencies:
  sprintf: '4.0.0'
dev_dependencies:
  test: any